import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import dynamic from 'next/dynamic';
const NavBar = dynamic(() => import('../src/components/NavBar'), { ssr: false });
import ClientProviders from "../src/components/ClientProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: any }) {
  const CP: any = ClientProviders;
  return (
    <html lang="en">
      <body className={`force-light`}>
        <Toaster position="bottom-center" />
        <CP>
          <NavBar />
          <main className="gf-main-container">
            {children}
          </main>
        </CP>
      </body>
    </html>
  );
}
